### ISSUE TITLE
How to use maven to bring this into project?

### ISSUE THREAD

**Issue by christopinka-vp** [IBM/API4JSON#16]
I've tried
```
 <groupId>com.github.wnm3</groupId>
    <artifactId>API4JSON</artifactId>
    <version>2.0.2</version>
 
    
    Do I need to build and install the jar manually? Thanks

**Comment by wnm3** [comment]
Hi Christo:

From https://search.maven.org/artifact/com.github.wnm3/API4JSON/2.0.2/jar
you can use:
<dependency>
  <groupId>com.github.wnm3</groupId>
  <artifactId>API4JSON</artifactId>
  <version>2.0.2</version>
</dependency>

**Comment by wnm3** [comment]
You can build them if you go into the project directory and use:
mvn clean install

Or if you are in Eclipse, right click and select Run as Maven... and use "clean install" as the goals
